//==============================================
// Generated by http://www.My2ndGeneration.com
//==============================================

using System;

using Tiraggo.Core;
using Tiraggo.Interfaces;
using Tiraggo.DynamicQuery;

namespace Watch_List
{
	public partial class MailPreferencesQuery : tgMailPreferencesQuery
	{
		public MailPreferencesQuery()
		{

		}
	}
}	
